### ISSUE TITLE
Stream Arn variable not set

### ISSUE THREAD

**Issue by franz-josef-kaiser** [usefulio/serverless-dynamodb-triggers#1]
In your `s-function.json` you are using a variable inside [`events::config::streamArn`](https://github.com/usefulio/serverless-dynamodb-triggers/blob/d4434555133316107413b1001a7e7d3bedacad23/processStreamEvent/s-function.json#L20) that is undefined and will throw an error. 

Where _should_ it have been defined?

**Comment by ianserlin** [comment]
When you first clone the project you'll need to do `sls init` to tell serverless to create your local `_meta` folder with the associated json config files for the `region`s and `stage`s you choose. After that, once you do `sls resources deploy`, the `${exampleDynamoTableStreamArn}` that the `streamArn` in `s-function.json` references will have a value in your `_meta/variables/s-variables-{stage}-{region}.json` file. This value is specific to your deployment and the ARN that aws gives you for your particular DynamoDB Table Stream.

After setting up the project and deploying ("creating") your resources (including DynamoDB, which is being specified in the `s-resources-cf.json`), the environment variables for your function will be supplied properly on local run and function deploy.

Hope that helps clear some things up!

**Comment by franz-josef-kaiser** [comment]
@ianserlin thanks for the extensive explanation! Any idea how to **update** the `_meta/variables/s-variables-{stage}-{region}.json` file? I tried copying your project files into my project (which only had a single Lambda function plus some DynamoDB tables) and then hit the wall as I have no idea how to add the new variables.

**Comment by ianserlin** [comment]
Yup, if you already have a serverless project that you're copying these files into, then make sure you are also copying in the relevant portions of `s-resources-cf-.json` and then do an `sls resources deploy`. That command will provision the dynamodb table, etc and update your `_meta` configuration files.

It's the `s-resources-cf.json` file that tells serverless and cloudformation to create a dynamodb table for you and set up the stream ARN and place the stream arn into your `_meta` variables.

If you just clone this entire project, do an `sls init` and then `sls resources deploy` inside your cloned directory..

**Comment by franz-josef-kaiser** [comment]
Thanks for sticking to it. My main problem is, that the `_meta/variables/s-variables-{stage}-{region}.json` file does not receive that variable. I `diff`ed all files and everything updates properly – aside from the variables file. Ran everything even with the `--debug` flag set and I can see nothing wrong there. The problem _seem_ to be related to [this serverless issue](https://github.com/serverless/serverless/issues/1043).

**Comment by ianserlin** [comment]
It may be that you are re-using `stage` names across a few different test serverless projects? That might cause some collision. Here's my terminal output, for posterity:

```
~/code/scratch : git clone git@github.com:usefulio/serverless-dynamodb-triggers.git
Cloning into 'serverless-dynamodb-triggers'...
remote: Counting objects: 36, done.
remote: Total 36 (delta 0), reused 0 (delta 0), pack-reused 36
Receiving objects: 100% (36/36), 7.25 KiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
~/code/scratch : cd serverless-dynamodb-triggers/
~/code/scratch/serverless-dynamodb-triggers master u= : sls project init
 _______                             __
|   _   .-----.----.--.--.-----.----|  .-----.-----.-----.
|   |___|  -__|   _|  |  |  -__|   _|  |  -__|__ --|__ --|
|____   |_____|__|  \___/|_____|__| |__|_____|_____|_____|
|   |   |             The Serverless Application Framework
|       |                           serverless.com, v0.5.5
`-------'

Serverless: Initializing Serverless Project...
Serverless: Enter a new stage name for this project:  (dev) triggersdev
Serverless: For the "triggersdev" stage, do you want to use an existing Amazon Web Services profile or create a new one?
  > Existing Profile
    Create A New Profile
Serverless: Select a profile for your project:
  > usefulio_ian
Serverless: Creating stage "triggersdev"...
Serverless: Select a new region for your stage:
  > us-east-1
    us-west-2
    eu-west-1
    eu-central-1
    ap-northeast-1
Serverless: Creating region "us-east-1" in stage "triggersdev"...
Serverless: Deploying resources to stage "triggersdev" in region "us-east-1" via Cloudformation (~3 minutes)...
Serverless: - Serverless: WARNING: This variable is not defined: exampleDynamoTableStreamArn
Serverless: Successfully deployed "triggersdev" resources to "us-east-1"
Serverless: Successfully created region "us-east-1" within stage "triggersdev"
Serverless: Successfully created stage "triggersdev"
Serverless: Successfully initialized project "serverless-dynamodb-triggers"
~/code/scratch/serverless-dynamodb-triggers master * u= : cat _meta/variables/s-variables-triggersdev-useast1.json
{
  "region": "us-east-1",
  "resourcesStackName": "serverless-dynamodb-triggers-triggersdev-r",
  "iamRoleArnLambda": "arn:aws:iam::00000000000:role/serverless-dynamodb-triggers-trigger-IamRoleLambda-186WFUBDRJOJN",
  "exampleDynamoTableStreamArn": "arn:aws:dynamodb:us-east-1:00000000000:table/triggersdev-serverless-dynamodb-triggers-example/stream/2016-06-19T22:56:24.319"
}
```
